// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiCiG_VOG1LoL98xEbLLsQPqtTRvli8KE',
    appId: '1:395080290453:web:43e50d78d9f11fc0808b9c',
    messagingSenderId: '395080290453',
    projectId: 'nhom-86edd',
    authDomain: 'nhom-86edd.firebaseapp.com',
    storageBucket: 'nhom-86edd.firebasestorage.app',
    measurementId: 'G-WRCR9L0MRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WlK9F6ujnFo5_ck3m3fQdSGu4uYH7yA',
    appId: '1:395080290453:android:ea9130f242564db1808b9c',
    messagingSenderId: '395080290453',
    projectId: 'nhom-86edd',
    storageBucket: 'nhom-86edd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJsN26y04OB1FyRN9tPhm8lsLX8_svWz4',
    appId: '1:395080290453:ios:b09bd3437bcd6ffb808b9c',
    messagingSenderId: '395080290453',
    projectId: 'nhom-86edd',
    storageBucket: 'nhom-86edd.firebasestorage.app',
    iosBundleId: 'com.example.doanNhomCuoiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJsN26y04OB1FyRN9tPhm8lsLX8_svWz4',
    appId: '1:395080290453:ios:b09bd3437bcd6ffb808b9c',
    messagingSenderId: '395080290453',
    projectId: 'nhom-86edd',
    storageBucket: 'nhom-86edd.firebasestorage.app',
    iosBundleId: 'com.example.doanNhomCuoiky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiCiG_VOG1LoL98xEbLLsQPqtTRvli8KE',
    appId: '1:395080290453:web:a20c386c9c6c4657808b9c',
    messagingSenderId: '395080290453',
    projectId: 'nhom-86edd',
    authDomain: 'nhom-86edd.firebaseapp.com',
    storageBucket: 'nhom-86edd.firebasestorage.app',
    measurementId: 'G-2576J7FBR6',
  );
}
